### ISSUE TITLE
ST_Centroid bug

### ISSUE THREAD

**Issue by beautifulpython** [zilliztech/GIS#100]
I got different output when I use specific wkt as input to the ST_Centroid function (compared to geospark).
---
---
- geospark test :
  spark.sql("SELECT ST_Centroid(ST_GeomFromWKT('MULTIPOLYGON ( ((0 0, 1 4, 1 0,0 0)), ((0 0,1 0,0 1,0 0)) )'))").show(1,0)
  output : POINT (0.7777777777777778 1.6666666666666667)
---

- GIS test :
  wkt_arrow_array = {MULTIPOLYGON ( ((0 0, 1 4, 1 0,0 0)), ((0 0,1 0,0 1,0 0)) )}
  zilliz::gis::ST_Centroid(wkt_arrow_array)
 output : POINT (0.6 1.13333333333333)

- postgis test :
  select st_astext(st_centroid('MULTIPOLYGON ( ((0 0, 1 4, 1 0,0 0)), ((0 0,1 0,0 1,0 0)) )'::geometry));
  output : POINT(0.6 1.13333333333333)

**Comment by nezha2017** [comment]
If arctern's output is the same as postgis, so I think this is not a problem.
