### ISSUE TITLE
ST_Contains  bug

### ISSUE THREAD

**Issue by beautifulpython** [zilliztech/GIS#105]
I got different output when I use specific wkt as input to the ST_Contains function (compared to geospark).
---
---
- geospark test :
   spark.sql("SELECT ST_Contains( ST_GeomFromWKT('POLYGON ((0 0,4 0,4 4,0 4,0 0))') , ST_GeomFromWKT('POINT (4 0)') )").show(false)
  output : true
---

- GIS test :
  wkt_arrow_array1 = { POLYGON ((0 0,4 0,4 4,0 4,0 0))}
  wkt_arrow_array2 = { POINT (4 0)}
  zilliz::gis::ST_Contains(wkt_arrow_array1,wkt_arrow_array2)
 output : false

- postgis test :
  select st_contains('POLYGON ((0 0,4 0,4 4,0 4,0 0))'::geometry,'POINT (4 0)'::geometry);
  output : false

**Comment by nezha2017** [comment]
If arctern's output is the same as postgis, so I think this is not a problem.
