### ISSUE TITLE
ST_Buffer bug

### ISSUE THREAD

**Issue by beautifulpython** [zilliztech/GIS#108]
I got different output when I use specific wkt as input to the ST_Buffer function (compared to geospark).
---
---
- geospark test :
spark.sql("SELECT ST_Buffer( ST_GeomFromWKT('MULTIPOLYGON ( ((0 0, 1 4, 1 0,0 0)), ((0 0,1 0,0 1,0 0)) )') , 0)").show(1,0)
  output : POLYGON ((0.2 0.8, 1 4, 1 0, 0.2 0.8))
---

- GIS test :
  wkt_arrow_array = {MULTIPOLYGON ( ((0 0, 1 4, 1 0,0 0)), ((0 0,1 0,0 1,0 0)) ) }
  zilliz::gis::ST_Buffer(wkt_arrow_array,0)
 output : POLYGON ((0 0,0 1,0.2 0.8,1 4,1 0,0 0))

- postgis test :
  select st_astext(st_buffer('MULTIPOLYGON ( ((0 0, 1 4, 1 0,0 0)), ((0 0,1 0,0 1,0 0)) )'::geometry,0))
  output : POLYGON((0 0,0 1,0.2 0.8,1 4,1 0,0 0))

**Comment by nezha2017** [comment]
what's the out of postgis on ST_Buffer ? @xiaocai2333 @beautifulpython

**Comment by nezha2017** [comment]
If arctern's output is the same as postgis, so I think this is not a problem.
