### ISSUE TITLE
st_envelope_udf empty geoms results different with postgis

### ISSUE THREAD

**Issue by liangliu** [zilliztech/GIS#135]
our sql:
select st_envelope_udf(geos) as geos from test_envelope
input:
{"geos": "POLYGON EMPTY"}
{"geos": "LINESTRING EMPTY"}
{"geos": "POINT EMPTY"}
{"geos": "MULTIPOLYGON EMPTY"}
{"geos": "MULTILINESTRING EMPTY"}
{"geos": "MULTIPOINT EMPTY"}
{"geos": "GEOMETRYCOLLECTION EMPTY"}

result:
{"geos":"POINT (0 0)"}
{"geos":"POINT (0 0)"}
{"geos":"POINT (0 0)"}
{"geos":"POINT (0 0)"}
{"geos":"POINT (0 0)"}
{"geos":"POINT (0 0)"}
{"geos":"POINT (0 0)"}

in POSTGIS
sqls:
select st_astext(st_envelope('POLYGON EMPTY'::geometry));
select st_astext(st_envelope('LINESTRING EMPTY'::geometry));
select st_astext(st_envelope('POINT EMPTY'::geometry));
select st_astext(st_envelope('MULTIPOLYGON EMPTY'::geometry));
select st_astext(st_envelope('MULTILINESTRING EMPTY'::geometry));
select st_astext(st_envelope('MULTIPOINT EMPTY'::geometry));
select st_astext(st_envelope('GEOMETRYCOLLECTION EMPTY'::geometry));

result:
 POLYGON EMPTY
 LINESTRING EMPTY
 POINT EMPTY
 MULTIPOLYGON EMPTY
 MULTILINESTRING EMPTY
 MULTIPOINT EMPTY
 GEOMETRYCOLLECTION EMPTY

**Comment by nezha2017** [comment]
I'm working on it

**Comment by liangliu** [comment]
this is fixed and verified
