### ISSUE TITLE
ST_Area bug

### ISSUE THREAD

**Issue by beautifulpython** [zilliztech/GIS#97]
I got different output when I use specific wkt as input to the ST_Area function (compared to geospark).
---
---
- geospark test :
  spark.sql("SELECT ST_Area(ST_GeomFromWKT('LINESTRING (0 0, 1 0, 1 1, 0 0)'))").show(1,0)
  output : 0

  spark.sql("SELECT ST_Area(ST_GeomFromWKT('MULTIPOLYGON ( ((0 0, 1 4, 1 0,0 0)), ((0 0,1 0,0 1,0 0)) ) '))").show(1,0)
  output : 1.5
---

- GIS test :
  wkt_arrow_array = {LINESTRING (0 0, 1 0, 1 1, 0 0) , MULTIPOLYGON ( ((0 0, 1 4, 1 0,0 0)), ((0 0,1 0,0 1,0 0)) ) }
  zilliz::gis::ST_Area(wkt_arrow_array)
 output : 0.5 ,2.5

**Comment by nezha2017** [comment]
this issue is fixed, #132
