### ISSUE TITLE
ST_Length bug

### ISSUE THREAD

**Issue by beautifulpython** [zilliztech/GIS#99]
I got different output when I use polygon's wkt as input to the ST_Length function (compared to geospark).
---
---
- geospark test :
  spark.sql("SELECT ST_Length(ST_GeomFromWKT('POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))'))").show(1,0)
  output : 4.0

  spark.sql("SELECT ST_Length(ST_GeomFromWKT('MULTIPOLYGON ( ((0 0, 1 4, 1 0,0 0)))'))").show(1,0)
  output : 9.123105625617661

  spark.sql("SELECT ST_Length(ST_GeomFromWKT('MULTIPOLYGON ( ((0 0, 0 4, 4 4, 4 0, 0 0)), ((0 0, 0 1, 4 1, 4 0, 0 0)) )'))").show(1,0)
  output : 26.0
---

- GIS test :
  wkt_arrow_array = {POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0)) ,MULTIPOLYGON ( ((0 0, 1 4, 1 0,0 0)) ) , MULTIPOLYGON ( ((0 0, 0 4, 4 4, 4 0, 0 0)), ((0 0, 0 1, 4 1, 4 0, 0 0)) )}
  zilliz::gis::ST_Area(wkt_arrow_array)
 output : 0 , 0 , 0 

- postgis test 
  output : 0 , 0 , 0

**Comment by nezha2017** [comment]
If arctern's output is the same as postgis, so I think this is not a problem.
